# Generated by Django 5.2.7 on 2026-02-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fruit', 'Fresh Fruits'), ('vegetable', 'Daily Vegetables'), ('dairy', 'Dairy Products'), ('Grains', 'Grains & Pulses'), ('Batter', 'Batter,Breads & Chapati'), ('spices', 'Spices & Herbs'), ('beverages', 'Beverages'), ('snacks', 'Snacks & Sweets'), ('others', 'Others')], max_length=20),
        ),
    ]
